apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In #NotIn, Exist, DoseNotExist
        values:
          - backend
      - key: tier
        operator: In
        values:
          - prod
      - key: team
        operator: In
        values:
          - "*"

  template:
    metadata:
      labels:
        app: nginx
        tier: prod
        team: core-banking
    spec:
      containers:
        - name: nginx
          image: nginx:latest
