apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: writer
      image: curlimages/curl
      command: ["sleep", "1000000"]
      env:
        - name: TZ
          value: Asia/tehran
        - name: POD_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: NodeId
          value: "120$(POD_INDEX)"
        - name: environment
          valueFrom:
            configMapKeyRef:
              name: sample-cm
              key: env
      volumeMounts:
        - name: secret-volume
          mountPath: /data-secret
          readOnly: true # Best practice for secrets
  volumes:
    - name: secret-volume
      secret:
        secretName: sample-secret
