apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  namespace: daneshkar
  labels:
    app: nginx
    tier: prod
    team: core-banking
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 4
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: prod
        team: core-banking
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          command:
            [
              "/bin/sh",
              "-c",
              "echo 'Job started'; sleep 90; echo 'Job completed'",
            ]
      restartPolicy: OnFailure
