apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-example-pod
spec:
  volumes:
    - name: shared-storage
      gitRepo:
        repository: https://github.com/Macstar-hub/daneshkar-docs.git
        revision: master
        directory: .
  containers:
    - name: sample-pod
      image: curlimages/curl
      command: ["sleep", "1000000"]
      volumeMounts:
        - name: shared-storage
          mountPath: /data
