apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: daneshkar
  labels:
    app: nginx
  annotations:
    daneshkar/component: payment-app
spec:
  # nodeSelector:
  #   gpu: "true"
  containers:
    - image: nginx:latest
      imagePullPolicy: IfNotPresent
      # command: ["nginx", "-c", "/etc/nginx/nginx.conf"]
      name: nginx
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 300m
          memory: 300Mi
      env:
        - name: TZ
          value: Asia/Tehran
      # livenessProbe:
      #   httpGet:
      #     path: /health
      #     port: 8080
      #     httpHeaders:
      #       - name: "Authorize Brear"
      #         value: "eyckbdcvldabvclvoqvqrvmlkcslssdddswcvw=="
      # initialDelaySeconds: 45
      # periodSeconds: 15
      # failurThreshold: 3

      # livenessProbe:
      #   tcpsocket:
      #     port: 8080
      #   initialDelaySeconds: 15
      #   periodSeconds: 3
      #   failurThreshold: 1

      # livenessProbe:
      #   exec:
      #     command:
      #     - curl
      #     - http://localhost:80
      #   initialDelaySeconds: 15
      #   periodSeconds: 3
      #   failurThreshold: 1

  restartPolicy: Always
