apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
spec:
  replicas: 3
  selector:
    app: frontend
template:
  metadata:
    labels:
      app: backend
  spec:
    containers:
      - name: frontend
        image: nginx:v2
        imagePullPolicy: IfNotPresent
        command: ["nginx", "-c", "/etc/nginx/nginx.conf"]
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1500m
            memory: 10Gi
        env:
          - name: TZ
            value: Asia/Tehran
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
              - name: "Authorize Brear"
                value: "eyckbdcvldabvclvoqvqrvmlkcslssdddswcvw=="
          initialDelaySeconds: 45
          periodSeconds: 15
          failurThreshold: 3
